{'/v1/a-prefix/endpoint-one': Route(handler=<function post at 0x100be2620>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/a-prefix/endpoint-one$'), parameters=[], name='database_1.post', uri='/v1/a-prefix/endpoint-one'),
 '/v1/a-prefix/endpoint-one/': Route(handler=<function post at 0x100be2620>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/a-prefix/endpoint-one/$'), parameters=[], name='database_1.post', uri='/v1/a-prefix/endpoint-one/'), 
 '/v1/a-prefix/endpoint-two': Route(handler=<sanic.views.CompositionView object at 0x101f65e10>, methods=frozenset({'GET', 'POST'}), pattern=re.compile('^/v1/a-prefix/endpoint-two$'), parameters=[], name='database_1.post', uri='/v1/a-prefix/endpoint-two'), 
 '/v1/a-prefix/endpoint-two/': Route(handler=<sanic.views.CompositionView object at 0x100bf94a8>, methods=frozenset({'GET', 'POST'}), pattern=re.compile('^/v1/a-prefix/endpoint-two/$'), parameters=[], name='database_1.post', uri='/v1/a-prefix/endpoint-two/'), '
 /v1/another-prefix/endpoint-three': Route(handler=<function post at 0x101f70510>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/another-prefix/endpoint-three$'), parameters=[], name='api_1.post', uri='/v1/another-prefix/endpoint-three'), 
 '/v1/another-prefix/endpoint-three/': Route(handler=<function post at 0x101f70510>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/another-prefix/endpoint-three/$'), parameters=[], name='api_1.post', uri='/v1/another-prefix/endpoint-three/'), 
 '/v1/another-prefix/endpoint-four': Route(handler=<function post at 0x101f70598>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/another-prefix/endpoint-four$'), parameters=[], name='api_1.post', uri='/v1/another-prefix/endpoint-four'), 
 '/v1/another-prefix/endpoint-four/': Route(handler=<function post at 0x101f70598>, methods=frozenset({'GET'}), pattern=re.compile('^/v1/another-prefix/endpoint-four/$'), parameters=[], name='api_1.post', uri='/v1/another-prefix/endpoint-four/'), 
 '/healthcheck': Route(handler=<function health at 0x101f70620>, methods=frozenset({'GET'}), pattern=re.compile('^/healthcheck$'), parameters=[], name='health', uri='/healthcheck'), 
 '/healthcheck/': Route(handler=<function health at 0x101f70620>, methods=frozenset({'GET'}), pattern=re.compile('^/healthcheck/$'), parameters=[], name='health', uri='/healthcheck/'), 
 '/test': Route(handler=<sanic.views.CompositionView object at 0x101f65e48>, methods=frozenset({'GET', 'POST'}), pattern=re.compile('^/test$'), parameters=[], name='test', uri='/test'), 
 '/test/': Route(handler=<sanic.views.CompositionView object at 0x101f65da0>, methods=frozenset({'GET', 'POST'}), pattern=re.compile('^/test/$'), parameters=[], name='test', uri='/test/')}